--- #test phase
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        hbm2ddl:
          auto: create

logging:
  level:
    org:
      hibernate:
        type: trace

--- #development phase
spring:
  confing:
    activate:
      on-profile: development
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        hbm2ddl:
          auto: create
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/rockpell?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    properties:
#      hibernate:
#        default_batch_fetch_size: 100
#        hbm2ddl:
#          auto: update

logging:
  level:
    org:
      hibernate:
        type: trace